PackageIdentifier: TestPublisher.TestApp3
PackageName: TestApp3
Moniker: TestApp
PackageVersion: 1.0.0.0
Publisher: TestPublisher
Author: TestPublisher
ShortDescription: TestPhrase "spoof"
Description: TestPhrase "doodoo"
PackageUrl: https://www.microsoft.com/openjdk
License: GPL2 with Classpath Exception.
LicenseUrl: https://openjdk.java.net/legal/gplv2+ce.html
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://aka.ms/download-jdk/microsoft-jdk-11.0.12.7.1-windows-x64.msi
  InstallerSha256: EA703299BDE8B840A291C86B597E7AF74F29BA5976082B0A7D16DC1D36668CE7
  Scope: machine
  InstallerLocale: en-US
  ProductCode: "{0D2DCFF8-7746-445B-B643-9E85ABE01173}"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0