# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: TestPublisher.TestApp2
PackageVersion: 0.18.95.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/Jackett/Jackett/releases/download/v0.18.95/Jackett.Installer.Windows.exe
  InstallerSha256: 2153A82FD2C519BEB48A842F3C24F2FA7909A674BCB9B570DF3A598715DED1B0
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
